kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: A/LaYgwVhvPK2A5xC2b4et7CboVoaibFl5PzYSNOq8A=
      - identity: {}
